'use client';
/* Native links deliberately unload guest state and avoid route prefetch. */
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { MAX_BLOCKS, RULES, SAMPLES, editHistory, freshExecution, moveBlock, redo, starterProject, stepProject, undo, type Block, type History, type Project, type RuleId, type Sample, type SampleId } from '@/lib/sorting-garden/runtime';
import './studio.css';
const titles = { start: 'When Run is pressed', sample: 'Use a sample card', rule: 'Choose a rule', show: 'Show the basket' };
function SamplePicture({ sample }: { sample: Sample }) { return <svg viewBox="0 0 120 100" width="100" height="84" aria-hidden="true">{sample.shape === 'round' ? <><circle cx="60" cy="56" r="32" fill={sample.color === 'red' ? '#c64a3b' : '#4e8551'} stroke="#173b29" strokeWidth="3"/><path d="M60 24V10M61 18Q80 4 83 18Q76 26 61 18" fill="#4e8551" stroke="#173b29" strokeWidth="3"/></> : <><path d="M60 8Q112 53 60 91Q8 53 60 8" fill="#4e8551" stroke="#173b29" strokeWidth="3"/><path d="M60 23V82M60 47L43 37M60 63L80 48" fill="none" stroke="#173b29" strokeWidth="3"/></>}</svg>; }
// Match the server render, then enable controls only once React handles events.
const subscribeToHydration = () => () => {};
const clientReady = () => true;
const serverReady = () => false;
export default function SortingGarden() {
  const ready = useSyncExternalStore(subscribeToHydration, clientReady, serverReady);
  const [history, setHistory] = useState<History>(() => ({ past: [], present: starterProject(), future: [] }));
  const [execution, setExecution] = useState(freshExecution), [running, setRunning] = useState(false), [finished, setFinished] = useState(false);
  const [announcement, setAnnouncement] = useState('Starter blocks are ready. Press Run to see what they do.');
  const nextId = useRef(0), dragged = useRef<number | null>(null), blocks = history.present.workspace_state.blocks;
  useEffect(() => {
    if (!running) return;
    const timer = window.setTimeout(() => { const next = stepProject(history.present, execution); setExecution(next); if (next.status === 'done' || next.status === 'error') { setRunning(false); setAnnouncement(next.error || 'Your program finished. Look at the basket, then try changing a block.'); } }, 450);
    return () => window.clearTimeout(timer);
  }, [running, history.present, execution]);
  useEffect(() => {
    // A browser Back action can restore a page without remounting React.
    function restore(event: PageTransitionEvent) { if (event.persisted) { setRunning(false); setExecution(freshExecution()); setHistory({ past: [], present: starterProject(), future: [] }); setAnnouncement('A fresh guest garden is ready.'); } }
    window.addEventListener('pageshow', restore); return () => window.removeEventListener('pageshow', restore);
  }, []);
  function clearRun() { setRunning(false); setExecution(freshExecution()); }
  function edit(project: Project) { clearRun(); setHistory(h => editHistory(h, project)); setAnnouncement('Blocks changed. Run again to see the new result.'); }
  function replace(index: number, block: Block) { edit({ ...history.present, workspace_state: { blocks: blocks.map((b, i) => i === index ? block : b) } }); }
  function add(type: Block['type']) { if (blocks.length >= MAX_BLOCKS) return; const id = `added-${++nextId.current}`; const b: Block = type === 'sample' ? { id, type, sample: 'red-round' } : type === 'rule' ? { id, type, rule: 'color' } : { id, type }; edit({ ...history.present, workspace_state: { blocks: [...blocks, b] } }); setAnnouncement(`${titles[type]} added at the end. Use Move up or Move down to put it in order.`); }
  function startRun() { if (execution.status === 'done' || execution.status === 'error') setExecution(freshExecution()); setRunning(true); }
  function oneStep() { const next = stepProject(history.present, execution.status === 'done' || execution.status === 'error' ? freshExecution() : execution); setExecution(next); setAnnouncement(next.error || next.trace.at(-1)?.message || 'Ready.'); }
  function reset() { clearRun(); setHistory(h => editHistory(h, starterProject())); setAnnouncement('Starter blocks restored. You can undo this change.'); }
  function finish() { clearRun(); setHistory({ past: [], present: starterProject(), future: [] }); nextId.current = 0; setFinished(true); }
  const stage = execution.stage;
  return <div className="sorting-garden"><a className="sg-skip" href="#garden-main">Skip to the block workspace</a><header className="sg-header"><a href="/" className="sg-brand">SkillSprout</a><span>Sorting Garden · guest preview</span><button disabled={!ready} onClick={finish}>Finish for now</button></header>
  {finished ? <main id="garden-main" className="sg-finished"><h1>A good place to pause.</h1><p>Your guest blocks and run history have been cleared.</p><p>Off screen, find two safe household objects with a grown-up. Can you sort them by shape, then sort them a different way?</p><button onClick={() => { setFinished(false); setAnnouncement('Starter blocks are ready.'); }}>Start a fresh garden</button><a href="/">Back to SkillSprout</a></main> : <>
  <section className="sg-intro"><p className="sg-eyebrow">MAKE · TRY · WONDER</p><h1>Where should this fruit go?</h1><p>Press <strong>Run</strong>. Then choose the <strong>green round fruit</strong> in block 2. Does your rule still work?</p><p className="sg-label"><strong>Rules simulator — not trained AI.</strong> The computer follows the rule you choose. No account needed.</p></section>
  <main id="garden-main" className="sg-grid" tabIndex={-1}><section className="sg-workspace" aria-labelledby="blocks-title"><div className="sg-section-heading"><h2 id="blocks-title">Your blocks</h2><span>{blocks.length} / {MAX_BLOCKS}</span></div><p id="block-help">Read from top to bottom. Use the arrow buttons to change the order, or drag a block.</p>
  <div className="sg-toolbar" aria-label="Program controls"><button className="sg-run" onClick={startRun} disabled={!ready || running}>{execution.cursor > 0 && execution.status === 'paused' ? 'Continue run' : 'Run'}</button><button onClick={() => { setRunning(false); setAnnouncement('Paused. Continue or step when you are ready.'); }} disabled={!ready || !running}>Pause</button><button onClick={oneStep} disabled={!ready || running}>Step</button><button disabled={!ready} onClick={() => { clearRun(); setAnnouncement('Stage cleared. Your blocks are unchanged.'); }}>Clear stage</button></div>
  <ol className="sg-blocks" aria-describedby="block-help">{blocks.map((block, index) => <li key={block.id} className={`sg-block sg-${block.type}${execution.trace.at(-1)?.blockId === block.id ? ' sg-current' : ''}`} draggable={ready && !running} onDragStart={() => { dragged.current = index; }} onDragEnd={() => { dragged.current = null; }} onDragOver={e => { if (ready && !running) e.preventDefault(); }} onDrop={e => { e.preventDefault(); if (ready && !running && dragged.current !== null) edit(moveBlock(history.present, dragged.current, index)); dragged.current = null; }}><div className="sg-block-title"><span className="sg-number">{index + 1}</span><strong>{titles[block.type]}</strong></div>
  {block.type === 'sample' && <label className="sg-field">Sample card<select aria-label={`Sample card in block ${index + 1}`} value={block.sample} disabled={!ready || running} onChange={e => replace(index, { ...block, sample: e.target.value as SampleId })}>{SAMPLES.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
  {block.type === 'rule' && <label className="sg-field">Sorting rule<select aria-label={`Sorting rule in block ${index + 1}`} value={block.rule} disabled={!ready || running} onChange={e => replace(index, { ...block, rule: e.target.value as RuleId })}><option value="color">Color: red → fruit; otherwise → leaf</option><option value="shape">Shape: round → fruit; otherwise → leaf</option></select></label>}
  <div className="sg-block-actions"><button disabled={!ready || running || index === 0} aria-label={`Move ${titles[block.type]} up`} onClick={() => edit(moveBlock(history.present, index, index - 1))}>↑ Up</button><button disabled={!ready || running || index === blocks.length - 1} aria-label={`Move ${titles[block.type]} down`} onClick={() => edit(moveBlock(history.present, index, index + 1))}>↓ Down</button><button disabled={!ready || running} aria-label={`Remove ${titles[block.type]}`} onClick={() => edit({ ...history.present, workspace_state: { blocks: blocks.filter((_, i) => i !== index) } })}>Remove</button></div></li>)}</ol>
  <details><summary>Add a block</summary><div className="sg-toolbox">{(['start', 'sample', 'rule', 'show'] as const).map(type => <button key={type} disabled={!ready || running || blocks.length >= MAX_BLOCKS} onClick={() => add(type)}>{titles[type]}</button>)}</div></details><div className="sg-toolbar"><button disabled={!ready || running || !history.past.length} onClick={() => { clearRun(); setHistory(undo); setAnnouncement('Last block change undone.'); }}>Undo</button><button disabled={!ready || running || !history.future.length} onClick={() => { clearRun(); setHistory(redo); setAnnouncement('Block change restored.'); }}>Redo</button><button disabled={!ready} onClick={reset}>Reset starter</button></div></section>
  <div className="sg-observe"><section className="sg-stage" aria-labelledby="stage-title"><p className="sg-eyebrow">LOOK WHAT YOUR PROGRAM DID</p><h2 id="stage-title">The garden stage</h2><div className="sg-status" role="status" aria-live="polite">{ready ? announcement : 'Loading the garden controls…'}</div><noscript>This garden needs JavaScript to run. Enable it and reload, or try sorting safe objects with a grown-up off screen.</noscript>{execution.error && <p role="alert" className="sg-error">{execution.error}</p>}<div className="sg-baskets">{(['fruit', 'leaf'] as const).map(basket => <div key={basket} className={`sg-basket${stage?.basket === basket ? ' sg-filled' : ''}`}><h3>{basket === 'fruit' ? 'Fruit basket' : 'Leaf basket'}</h3>{stage?.basket === basket ? <><SamplePicture sample={stage.sample}/><p>{stage.sample.name}</p></> : <p className="sg-empty">Waiting for a card</p>}</div>)}</div>
  {stage && <p className="sg-feedback">{stage.basket === stage.sample.expected ? 'This card reached the matching basket. Try another card to test your rule.' : 'A fruit landed with the leaves! Your program followed the color rule. Try the shape rule instead.'}</p>}<details className="sg-why" open><summary>Why did it do that?</summary>{stage ? <><p><strong>Input:</strong> {stage.sample.name}.</p><p><strong>Your rule:</strong> {RULES[stage.rule]}</p><p><strong>Result:</strong> {stage.basket} basket. This is a fixed rule, not a learned prediction.</p></> : <p>Run the blocks to see the input, rule and result here.</p>}<ol aria-label="Execution trace">{execution.trace.map((t, i) => <li key={`${t.blockId}-${i}`}>{t.message}</li>)}</ol></details></section>
  <section className="sg-challenge"><h2>Make a mistake. Make it better.</h2><ol><li>Run the starter with the red round fruit.</li><li>Change the sample to green round fruit. Run again.</li><li>Change the rule to shape. Where does the fruit go now?</li></ol><p>Ask together: “Can one rule work for every real fruit?” These are pretend cards. Real objects are more varied.</p></section>
  <details className="sg-grownups"><summary>For grownups: purpose, privacy and preview limits</summary><p>A beginning-reader coding preview, with adult help where useful. This is not the toddler activity area or a complete reviewed course.</p><p>Children can observe a rule, test a counterexample and change the rule. There is no score or claim of mastery. Educational and family usability review is still pending.</p><p>Blocks stay in this page’s memory. Finish or refresh to clear them. Nothing is saved to a learner profile. This demo makes no learning API, AI, analytics, camera or microphone calls. Ordinary hosting requests still occur when loading the page.</p><p>Saving, model training and course progress are later milestones. No purchase is needed. Off screen: sort safe objects by shape together, then try a different rule.</p></details></div></main></>}
  <footer className="sg-footer">Small experiments. Real curiosity. <span>Guest work is not saved.</span></footer></div>;
}
